# Database URL
spring.datasource.url=${DB_URL}

# PostgreSQL username
spring.datasource.username=${DB_USERNAME}

# PostgreSQL password
spring.datasource.password=${DB_PASSWORD}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true