# Database URL pointing to your local instance and the astrotrack database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate properties
# 'update' automatically creates or updates database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console (great for learning!)
spring.jpa.show-sql=true
